server:
  servlet:
    context-path: /auth-service
  port: ${PORT:8998}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://database-aws.cv4moeoi4rwx.ap-southeast-1.rds.amazonaws.com:3306/fast_food_express_db
    username: admin
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  version: '2.3.0'
  api-docs:
    version: openapi_3_1
  cache:
    disabled: true

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000

gateway:
  url: ${GATEWAY_URL:http://localhost:8765}
